@startuml

class Solution41 {
    +main(String[])
}

class Sorter {

    +List<String> getInputInfo ()
    +List<String> organizeNames(List<String> nameList)
    +int countNames(List<String> nameList)
    +void writeToOutput(List<String> nameList, int names)
}

Solution41 --o Sorter

@enduml